// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/important-dates": {
            "post": {
                "description": "Calculates important dates based on a provided date of death.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Important Dates"
                ],
                "summary": "Get Important Dates",
                "parameters": [
                    {
                        "description": "Important Dates Payload",
                        "name": "importantDates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.GetImportantDates"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ImportantDateResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or missing/invalid date_of_death property",
                        "schema": {
                            "$ref": "#/definitions/internal.ApiError"
                        }
                    },
                    "422": {
                        "description": "The date_of_death cannot be in the future",
                        "schema": {
                            "$ref": "#/definitions/internal.ApiError"
                        }
                    }
                }
            }
        },
        "/api/ping": {
            "get": {
                "description": "check connection",
                "produces": [
                    "text/plain"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.GetImportantDates": {
            "type": "object",
            "properties": {
                "date_of_death": {
                    "type": "string"
                }
            }
        },
        "dtos.ImportantDateResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal.ApiError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Amparo API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
